# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29a21ac41cbc98c69caeefc5c22c27ceb51e2d71a07a03a7715e46e527d710c7a565974cee849b775944615a0f4b5d716d9efd71ffcd2e4146c4110d3d0f677d

test:
  secret_key_base: 57b02e4756741744b470bce5f189ed0496f67d41e9b27e20781863be93731e5b2fba227a85c54211cfb59f0555be4ab38069bc1c75ef981f77dcd594063988a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
